version: '3.6'
services:
  wg:
    image: weejewel/wg-easy
    restart: always
    environment:
      - WG_HOST=orangenal-home.xyz
      - PASSWORD=$PASSWORD
    ports:
      - "51820:51820"
      - "51821:51821"
    volumes:
      - '~/.wg-easy:/etc/wireguard'
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      