version: '3.6'
services:
  bot:
    image: bot
    restart: always
    environment:
      - TELEGRAM_KEY=value
      - MAC_ADDRESS=value
      - ADMIN_PASSWORD=value
    volumes:
      -$HOME/bot:/app/volume:rw
      -$HOME/torrent:/app/torrent:rw